import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main sidebar for The Open Path documentation with proper ordering
  mainSidebar: [
    'index',
    {
      type: 'category',
      label: 'The Open Path',
      items: [{type: 'autogenerated', dirName: 'TheOpenPath'}],
    },
    {
      type: 'category',
      label: 'The Flourishing Start',
      items: [{type: 'autogenerated', dirName: 'TheFlourishingStart'}],
    },
    {
      type: 'category',
      label: 'Ecological Integrity',
      items: [{type: 'autogenerated', dirName: 'EcologicalIntegrity'}],
    },
    {
      type: 'category',
      label: 'Universal Basic Needs',
      items: [{type: 'autogenerated', dirName: 'UniversalBasicNeeds'}],
    },
    {
      type: 'category',
      label: 'Global Health & Disease Eradication',
      items: [{type: 'autogenerated', dirName: 'GlobalHealth_DiseaseEradication'}],
    },
    {
      type: 'category',
      label: 'Global Peace & Cooperation',
      items: [{type: 'autogenerated', dirName: 'GlobalPeace_Cooperation'}],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        'Methodology',
        'Glossary',
        'CONTRIBUTING',
        'CODE_OF_CONDUCT',
        'LICENSE',
        'Community_Hub',
      ],
    },
  ],
};

export default sidebars;
